app = "cryptoview"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1

[env]
  APP_NAME = "Cryptoview"
  APP_URL = "https://cryptoview.wilcokuyper.com"
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  SESSION_DRIVER = "database"
  CACHE_STORE = "file"
  QUEUE_CONNECTION = "sync"
  DB_CONNECTION = "pgsql"
  SESSION_SECURE_COOKIE = "true"
  SESSION_DOMAIN = "cryptoview.wilcokuyper.com"

[deploy]
  release_command = "sh -c 'php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force'"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
